//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarworldNewWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int id { get; set; }
        public string name { get; set; }
        public string picture { get; set; }
        public Nullable<int> lithuyet { get; set; }
        public Nullable<int> casestudy { get; set; }
        public Nullable<int> workshop { get; set; }
        public string address { get; set; }
        public Nullable<int> thoiluong { get; set; }
        public Nullable<System.DateTime> khaigiang { get; set; }
        public Nullable<double> hocphi { get; set; }
        public string thoigianhoc { get; set; }
        public Nullable<System.DateTime> handangki { get; set; }
        public string noichung { get; set; }
        public string doituong { get; set; }
        public string ghichu { get; set; }
        public string gioithieu { get; set; }
        public Nullable<bool> showOnSlider { get; set; }
    }
}
