//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarworldNewWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomImage
    {
        public int id { get; set; }
        public string imageCategory { get; set; }
        public string imageURL { get; set; }
    }
}
