//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarworldNewWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tailieu
    {
        public int id { get; set; }
        public string name { get; set; }
        public string authorname { get; set; }
        public string company { get; set; }
        public string loimodau { get; set; }
        public string gioithieuchung { get; set; }
        public string fileURL { get; set; }
        public string imageUrl { get; set; }
        public string noidung { get; set; }
        public string authorURL { get; set; }
        public string category { get; set; }
    }
}
