//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarworldNewWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int id { get; set; }
        public string name { get; set; }
        public string congty { get; set; }
        public string caunoi { get; set; }
        public string gioithieu { get; set; }
        public string picture { get; set; }
    }
}
